### PR TITLE
Bump to Pulsar 2.8.2

### PR DESCRIPTION
**Pull request by 315157973**
### Motivation
Bump to Pulsar 2.8.2

@codelipenghui  Please help me push the docker images to the docker hub, and then review this PR. Thanks.

### CODE REVIEW

**Review by lhotari — CHANGES_REQUESTED** [review]
PR #180 should be merged before this change.

**Review by lhotari — APPROVED** [review]

**Comment by lhotari** [comment]
It seems that #188 should also be resolved before switching to Pulsar 2.8.x .

**Comment by lhotari** [comment]
Failures in CI which points to #188. I'll push a fix to this PR.
```
Unrecognized VM option 'PrintGCTimeStamps'                    
Error: Could not create the Java Virtual Machine.             
Error: A fatal exception has occurred. Program will exit.     
Unrecognized VM option 'PrintGCTimeStamps'                    
Error: Could not create the Java Virtual Machine.             
Error: A fatal exception has occurred. Program will exit.     
```

**Review by lhotari — APPROVED** [review]

**Review by lhotari — CHANGES_REQUESTED** [review]
Postpone merging until there's a decision whether we should go forward with switching to Pulsar 2.8.x in the helm chart because of a known issue with Zookeeper (https://issues.apache.org/jira/browse/ZOOKEEPER-3988 / https://github.com/apache/pulsar/issues/11070 ).

Mailing list discussion: https://lists.apache.org/thread/619tpn6q5xbbhngwsmhtq3121vhjxpt4

**Comment by eolivelli** [comment]
Also, why should we ship 2.8 as default instead of 2.9.1?

**Comment by lhotari** [comment]
> Also, why should we ship 2.8 as default instead of 2.9.1?

I guess it could be about doing one step at a time (2.7.x -> 2.8.x, then 2.8.x->2.9.x) and also about stability.

**Comment by lhotari** [comment]
I created a PR #195 which adds better logging to CI which would help investigating CI failures. I have observed the "ZK TLS Only" CI job failing, presumably with the known problem. However it would be nice to see the logs too once #195 is reviewed and merged.

**Comment by ckdarby** [comment]
> > Also, why should we ship 2.8 as default instead of 2.9.1?
> 
> I guess it could be about doing one step at a time (2.7.x -> 2.8.x, then 2.8.x->2.9.x) and also about stability.

It would also be community friendly to do 2.8.X as a helm release version and *then* 2.9.X as it allows the community to run 2.8 from a helm chart and not need to override tags.

**Comment by lhotari** [comment]
I have created #202 as a workaround for the Zookeeper issue (when TLS is enabled).

**Comment by lhotari** [comment]
based on the logs, it looks like the `pulsar-bookkeeper-verify-clusterid` container fails: https://github.com/apache/pulsar-helm-chart/blob/a919f309c6d73342196dbaf6bf146cfda8d9e8e8/charts/pulsar/templates/pulsar-cluster-initialize.yaml#L61-L73 . I wonder why `pulsar-bookkeeper-verify-clusterid`.

```
[pod/pulsar-ci-pulsar-init-pzc88/pulsar-bookkeeper-verify-clusterid] 14:22:08.341 [main-SendThread(pulsar-ci-zookeeper:2281)] INFO  org.apache.zookeeper.ClientCnxn - Opening socket connection to server pulsar-ci-zookeeper/10.244.1.11:2281.
[pod/pulsar-ci-pulsar-init-pzc88/pulsar-bookkeeper-verify-clusterid] 14:22:08.346 [main-SendThread(pulsar-ci-zookeeper:2281)] INFO  org.apache.zookeeper.ClientCnxn - SASL config status: Will not attempt to authenticate using SASL (unknown error)
[pod/pulsar-ci-pulsar-init-pzc88/pulsar-bookkeeper-verify-clusterid] 14:22:38.987 [main-SendThread(pulsar-ci-zookeeper:2281)] WARN  org.apache.zookeeper.ClientCnxn - Client session timed out, have not heard from server in 30726ms for session id 0x0
[pod/pulsar-ci-pulsar-init-pzc88/pulsar-bookkeeper-verify-clusterid] 14:22:39.125 [main-SendThread(pulsar-ci-zookeeper:2281)] WARN  org.apache.zookeeper.ClientCnxn - Session 0x0 for sever pulsar-ci-zookeeper/10.244.1.11:2281, Closing socket connection. Attempting reconnect except it is a SessionExpiredException.
[pod/pulsar-ci-pulsar-init-pzc88/pulsar-bookkeeper-verify-clusterid] org.apache.zookeeper.ClientCnxn$SessionTimeoutException: Client session timed out, have not heard from server in 30726ms for session id 0x0
[pod/pulsar-ci-pulsar-init-pzc88/pulsar-bookkeeper-verify-clusterid] 	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1258) [org.apache.zookeeper-zookeeper-3.6.3.jar:3.6.3]
[pod/pulsar-ci-pulsar-init-pzc88/pulsar-bookkeeper-verify-clusterid] 14:22:43.496 [main] INFO  org.apache.zookeeper.ClientCnxnSocketNetty - channel is told closing
[pod/pulsar-ci-pulsar-init-pzc88/pulsar-bookkeeper-verify-clusterid] 14:22:43.686 [globalEventExecutor-1-1] WARN  org.apache.zookeeper.ClientCnxnSocketNetty - future isn't success.
[pod/pulsar-ci-pulsar-init-pzc88/pulsar-bookkeeper-verify-clusterid] io.netty.util.concurrent.DefaultPromise$LeanCancellationException: null
[pod/pulsar-ci-pulsar-init-pzc88/pulsar-bookkeeper-verify-clusterid] 	at io.netty.util.concurrent.DefaultPromise.cancel(...)(Unknown Source) ~[io.netty-netty-common-4.1.72.Final.jar:4.1.72.Final]
[pod/pulsar-ci-pulsar-init-pzc88/pulsar-bookkeeper-verify-clusterid] 14:22:43.706 [main] INFO  org.apache.zookeeper.ZooKeeper - Session: 0x0 closed
[pod/pulsar-ci-pulsar-init-pzc88/pulsar-bookkeeper-verify-clusterid] 14:22:43.721 [main-EventThread] INFO  org.apache.zookeeper.ClientCnxn - EventThread shut down for session: 0x0
[pod/pulsar-ci-pulsar-init-pzc88/pulsar-bookkeeper-verify-clusterid] 14:22:43.707 [main] ERROR org.apache.bookkeeper.meta.zk.ZKMetadataDriverBase - Failed to create zookeeper client to pulsar-ci-zookeeper:2281
[pod/pulsar-ci-pulsar-init-pzc88/pulsar-bookkeeper-verify-clusterid] org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
[pod/pulsar-ci-pulsar-init-pzc88/pulsar-bookkeeper-verify-clusterid] 	at org.apache.zookeeper.KeeperException.create(KeeperException.java:102) ~[org.apache.zookeeper-zookeeper-3.6.3.jar:3.6.3]
[pod/pulsar-ci-pulsar-init-pzc88/pulsar-bookkeeper-verify-clusterid] 	at org.apache.bookkeeper.zookeeper.ZooKeeperWatcherBase.waitForConnection(ZooKeeperWatcherBase.java:159) ~[org.apache.bookkeeper-bookkeeper-server-4.14.3.jar:4.14.3]
[pod/pulsar-ci-pulsar-init-pzc88/pulsar-bookkeeper-verify-clusterid] 	at org.apache.bookkeeper.zookeeper.ZooKeeperClient$Builder.build(ZooKeeperClient.java:260) ~[org.apache.bookkeeper-bookkeeper-server-4.14.3.jar:4.14.3]
[pod/pulsar-ci-pulsar-init-pzc88/pulsar-bookkeeper-verify-clusterid] 	at org.apache.bookkeeper.meta.zk.ZKMetadataDriverBase.initialize(ZKMetadataDriverBase.java:207) [org.apache.bookkeeper-bookkeeper-server-4.14.3.jar:4.14.3]
[pod/pulsar-ci-pulsar-init-pzc88/pulsar-bookkeeper-verify-clusterid] 	at org.apache.bookkeeper.meta.zk.ZKMetadataBookieDriver.initialize(ZKMetadataBookieDriver.java:60) [org.apache.bookkeeper-bookkeeper-server-4.14.3.jar:4.14.3]
[pod/pulsar-ci-pulsar-init-pzc88/pulsar-bookkeeper-verify-clusterid] 	at org.apache.bookkeeper.meta.MetadataDrivers.runFunctionWithMetadataBookieDriver(MetadataDrivers.java:345) [org.apache.bookkeeper-bookkeeper-server-4.14.3.jar:4.14.3]
[pod/pulsar-ci-pulsar-init-pzc88/pulsar-bookkeeper-verify-clusterid] 	at org.apache.bookkeeper.meta.MetadataDrivers.runFunctionWithRegistrationManager(MetadataDrivers.java:372) [org.apache.bookkeeper-bookkeeper-server-4.14.3.jar:4.14.3]
[pod/pulsar-ci-pulsar-init-pzc88/pulsar-bookkeeper-verify-clusterid] 	at org.apache.bookkeeper.tools.cli.commands.bookies.InstanceIdCommand.apply(InstanceIdCommand.java:49) [org.apache.bookkeeper-bookkeeper-server-4.14.3.jar:4.14.3]
[pod/pulsar-ci-pulsar-init-pzc88/pulsar-bookkeeper-verify-clusterid] 	at org.apache.bookkeeper.bookie.BookieShell$WhatIsInstanceId.runCmd(BookieShell.java:1492) [org.apache.bookkeeper-bookkeeper-server-4.14.3.jar:4.14.3]
[pod/pulsar-ci-pulsar-init-pzc88/pulsar-bookkeeper-verify-clusterid] 	at org.apache.bookkeeper.bookie.BookieShell$MyCommand.runCmd(BookieShell.java:238) [org.apache.bookkeeper-bookkeeper-server-4.14.3.jar:4.14.3]
[pod/pulsar-ci-pulsar-init-pzc88/pulsar-bookkeeper-verify-clusterid] 	at org.apache.bookkeeper.bookie.BookieShell.run(BookieShell.java:2275) [org.apache.bookkeeper-bookkeeper-server-4.14.3.jar:4.14.3]
[pod/pulsar-ci-pulsar-init-pzc88/pulsar-bookkeeper-verify-clusterid] 	at org.apache.bookkeeper.bookie.BookieShell.main(BookieShell.java:2366) [org.apache.bookkeeper-bookkeeper-server-4.14.3.jar:4.14.3]
[pod/pulsar-ci-pulsar-init-pzc88/pulsar-bookkeeper-verify-clusterid] Exception in thread "main" com.google.common.util.concurrent.UncheckedExecutionException: Failed to create zookeeper client to pulsar-ci-zookeeper:2281
[pod/pulsar-ci-pulsar-init-pzc88/pulsar-bookkeeper-verify-clusterid] 	at org.apache.bookkeeper.tools.cli.commands.bookies.InstanceIdCommand.apply(InstanceIdCommand.java:61)
[pod/pulsar-ci-pulsar-init-pzc88/pulsar-bookkeeper-verify-clusterid] 	at org.apache.bookkeeper.bookie.BookieShell$WhatIsInstanceId.runCmd(BookieShell.java:1492)
[pod/pulsar-ci-pulsar-init-pzc88/pulsar-bookkeeper-verify-clusterid] 	at org.apache.bookkeeper.bookie.BookieShell$MyCommand.runCmd(BookieShell.java:238)
[pod/pulsar-ci-pulsar-init-pzc88/pulsar-bookkeeper-verify-clusterid] 	at org.apache.bookkeeper.bookie.BookieShell.run(BookieShell.java:2275)
[pod/pulsar-ci-pulsar-init-pzc88/pulsar-bookkeeper-verify-clusterid] 	at org.apache.bookkeeper.bookie.BookieShell.main(BookieShell.java:2366)
[pod/pulsar-ci-pulsar-init-pzc88/pulsar-bookkeeper-verify-clusterid] Caused by: org.apache.bookkeeper.meta.exceptions.MetadataException: Failed to create zookeeper client to pulsar-ci-zookeeper:2281
[pod/pulsar-ci-pulsar-init-pzc88/pulsar-bookkeeper-verify-clusterid] 	at org.apache.bookkeeper.meta.zk.ZKMetadataDriverBase.initialize(ZKMetadataDriverBase.java:227)
[pod/pulsar-ci-pulsar-init-pzc88/pulsar-bookkeeper-verify-clusterid] 	at org.apache.bookkeeper.meta.zk.ZKMetadataBookieDriver.initialize(ZKMetadataBookieDriver.java:60)
[pod/pulsar-ci-pulsar-init-pzc88/pulsar-bookkeeper-verify-clusterid] 	at org.apache.bookkeeper.meta.MetadataDrivers.runFunctionWithMetadataBookieDriver(MetadataDrivers.java:345)
[pod/pulsar-ci-pulsar-init-pzc88/pulsar-bookkeeper-verify-clusterid] 	at org.apache.bookkeeper.meta.MetadataDrivers.runFunctionWithRegistrationManager(MetadataDrivers.java:372)
[pod/pulsar-ci-pulsar-init-pzc88/pulsar-bookkeeper-verify-clusterid] 	at org.apache.bookkeeper.tools.cli.commands.bookies.InstanceIdCommand.apply(InstanceIdCommand.java:49)
[pod/pulsar-ci-pulsar-init-pzc88/pulsar-bookkeeper-verify-clusterid] 	... 4 more
[pod/pulsar-ci-pulsar-init-pzc88/pulsar-bookkeeper-verify-clusterid] Caused by: org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
[pod/pulsar-ci-pulsar-init-pzc88/pulsar-bookkeeper-verify-clusterid] 	at org.apache.zookeeper.KeeperException.create(KeeperException.java:102)
[pod/pulsar-ci-pulsar-init-pzc88/pulsar-bookkeeper-verify-clusterid] 	at org.apache.bookkeeper.zookeeper.ZooKeeperWatcherBase.waitForConnection(ZooKeeperWatcherBase.java:159)
[pod/pulsar-ci-pulsar-init-pzc88/pulsar-bookkeeper-verify-clusterid] 	at org.apache.bookkeeper.zookeeper.ZooKeeperClient$Builder.build(ZooKeeperClient.java:260)
[pod/pulsar-ci-pulsar-init-pzc88/pulsar-bookkeeper-verify-clusterid] 	at org.apache.bookkeeper.meta.zk.ZKMetadataDriverBase.initialize(ZKMetadataDriverBase.java:207)
[pod/pulsar-ci-pulsar-init-pzc88/pulsar-bookkeeper-verify-clusterid] 	... 8 more
[pod/pulsar-ci-pulsar-init-pzc88/pulsar-bookkeeper-verify-clusterid] 14:23:19.303 [epollEventLoopGroup-2-1] INFO  org.apache.zookeeper.ClientCnxnSocketNetty - SSL handler added for channel: [id: 0xaa063649]
Error from server (BadRequest): container "pulsar-ci-pulsar-init" in pod "pulsar-ci-pulsar-init-pzc88" is waiting to start: PodInitializing
```

I guess that the `bookie-init` has to finish first. Checking the logs for that.

**Comment by lhotari** [comment]
here's the [bookie-init failure](https://gist.githubusercontent.com/lhotari/1762ae76483596a3d49d9c0df1e4bb6d/raw/cdb58eb085b336fa961e9283807698552ca536ee/pulsar-ci-bookie-init-and-zk-logs.txt):
```
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] 14:45:47.975 [main] INFO  org.apache.zookeeper.ClientCnxnSocket - jute.maxbuffer value is 1048575 Bytes
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] 14:45:47.983 [main] INFO  org.apache.zookeeper.ClientCnxn - zookeeper.request.timeout value is 0. feature enabled=false
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] 14:45:48.046 [main-SendThread(pulsar-ci-zookeeper:2281)] INFO  org.apache.zookeeper.ClientCnxn - Opening socket connection to server pulsar-ci-zookeeper/10.244.1.11:2281.
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] 14:45:48.047 [main-SendThread(pulsar-ci-zookeeper:2281)] INFO  org.apache.zookeeper.ClientCnxn - SASL config status: Will not attempt to authenticate using SASL (unknown error)
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] 14:45:49.113 [epollEventLoopGroup-2-1] INFO  org.apache.zookeeper.ClientCnxnSocketNetty - SSL handler added for channel: [id: 0xe111b4a0]
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] 14:45:49.166 [epollEventLoopGroup-2-1] INFO  org.apache.zookeeper.ClientCnxn - Socket connection established, initiating session, client: /10.244.1.20:39420, server: pulsar-ci-zookeeper/10.244.1.11:2281
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] 14:45:49.172 [epollEventLoopGroup-2-1] INFO  org.apache.zookeeper.ClientCnxnSocketNetty - channel is connected: [id: 0xe111b4a0, L:/10.244.1.20:39420 - R:pulsar-ci-zookeeper/10.244.1.11:2281]
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] 14:46:03.784 [epollEventLoopGroup-2-1] INFO  org.apache.zookeeper.ClientCnxnSocketNetty - channel is disconnected: [id: 0xe111b4a0, L:/10.244.1.20:39420 ! R:pulsar-ci-zookeeper/10.244.1.11:2281]
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] 14:46:03.786 [epollEventLoopGroup-2-1] INFO  org.apache.zookeeper.ClientCnxnSocketNetty - channel is told closing
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] 14:46:03.810 [main-SendThread(pulsar-ci-zookeeper:2281)] WARN  org.apache.zookeeper.ClientCnxn - Session 0x0 for sever pulsar-ci-zookeeper/10.244.1.11:2281, Closing socket connection. Attempting reconnect except it is a SessionExpiredException.
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] org.apache.zookeeper.ClientCnxn$EndOfStreamException: channel for sessionid 0x0 is lost
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] 	at org.apache.zookeeper.ClientCnxnSocketNetty.doTransport(ClientCnxnSocketNetty.java:285) ~[org.apache.zookeeper-zookeeper-3.6.3.jar:3.6.3]
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] 	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1290) [org.apache.zookeeper-zookeeper-3.6.3.jar:3.6.3]
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] 14:46:05.650 [main-SendThread(pulsar-ci-zookeeper:2281)] INFO  org.apache.zookeeper.ClientCnxn - Opening socket connection to server pulsar-ci-zookeeper/10.244.1.11:2281.
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] 14:46:05.653 [main-SendThread(pulsar-ci-zookeeper:2281)] INFO  org.apache.zookeeper.ClientCnxn - SASL config status: Will not attempt to authenticate using SASL (unknown error)
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] 14:46:20.277 [epollEventLoopGroup-2-1] INFO  org.apache.zookeeper.ClientCnxnSocketNetty - SSL handler added for channel: [id: 0x20cc85f5]
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] 14:46:20.285 [epollEventLoopGroup-2-1] INFO  org.apache.zookeeper.ClientCnxn - Socket connection established, initiating session, client: /10.244.1.20:39662, server: pulsar-ci-zookeeper/10.244.1.11:2281
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] 14:46:20.289 [epollEventLoopGroup-2-1] INFO  org.apache.zookeeper.ClientCnxnSocketNetty - channel is connected: [id: 0x20cc85f5, L:/10.244.1.20:39662 - R:pulsar-ci-zookeeper/10.244.1.11:2281]
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] 14:46:30.746 [epollEventLoopGroup-2-1] INFO  org.apache.zookeeper.ClientCnxn - Session establishment complete on server pulsar-ci-zookeeper/10.244.1.11:2281, session id = 0x1000003b111025b, negotiated timeout = 30000
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] 14:46:32.021 [main-EventThread] INFO  org.apache.bookkeeper.zookeeper.ZooKeeperWatcherBase - ZooKeeper client is connected now.
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] 14:46:35.658 [main] INFO  org.apache.zookeeper.ClientCnxnSocketNetty - channel is told closing
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] 14:46:37.603 [epollEventLoopGroup-2-1] INFO  org.apache.zookeeper.ClientCnxnSocketNetty - channel is disconnected: [id: 0x20cc85f5, L:/10.244.1.20:39662 ! R:pulsar-ci-zookeeper/10.244.1.11:2281]
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] 14:46:37.603 [main-EventThread] INFO  org.apache.zookeeper.ClientCnxn - EventThread shut down for session: 0x1000003b111025b
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] 14:46:37.603 [main] INFO  org.apache.zookeeper.ZooKeeper - Session: 0x1000003b111025b closed
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] 14:46:37.608 [main] ERROR org.apache.bookkeeper.meta.zk.ZKMetadataDriverBase - Failed to create zookeeper client to pulsar-ci-zookeeper:2281
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] 	at org.apache.zookeeper.KeeperException.create(KeeperException.java:102) ~[org.apache.zookeeper-zookeeper-3.6.3.jar:3.6.3]
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] 	at org.apache.bookkeeper.zookeeper.ZooKeeperWatcherBase.waitForConnection(ZooKeeperWatcherBase.java:159) ~[org.apache.bookkeeper-bookkeeper-server-4.14.3.jar:4.14.3]
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] 	at org.apache.bookkeeper.zookeeper.ZooKeeperClient$Builder.build(ZooKeeperClient.java:260) ~[org.apache.bookkeeper-bookkeeper-server-4.14.3.jar:4.14.3]
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] 	at org.apache.bookkeeper.meta.zk.ZKMetadataDriverBase.initialize(ZKMetadataDriverBase.java:207) [org.apache.bookkeeper-bookkeeper-server-4.14.3.jar:4.14.3]
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] 	at org.apache.bookkeeper.meta.zk.ZKMetadataBookieDriver.initialize(ZKMetadataBookieDriver.java:60) [org.apache.bookkeeper-bookkeeper-server-4.14.3.jar:4.14.3]
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] 	at org.apache.bookkeeper.meta.MetadataDrivers.runFunctionWithMetadataBookieDriver(MetadataDrivers.java:345) [org.apache.bookkeeper-bookkeeper-server-4.14.3.jar:4.14.3]
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] 	at org.apache.bookkeeper.meta.MetadataDrivers.runFunctionWithRegistrationManager(MetadataDrivers.java:372) [org.apache.bookkeeper-bookkeeper-server-4.14.3.jar:4.14.3]
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] 	at org.apache.bookkeeper.tools.cli.commands.bookies.InstanceIdCommand.apply(InstanceIdCommand.java:49) [org.apache.bookkeeper-bookkeeper-server-4.14.3.jar:4.14.3]
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] 	at org.apache.bookkeeper.bookie.BookieShell$WhatIsInstanceId.runCmd(BookieShell.java:1492) [org.apache.bookkeeper-bookkeeper-server-4.14.3.jar:4.14.3]
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] 	at org.apache.bookkeeper.bookie.BookieShell$MyCommand.runCmd(BookieShell.java:238) [org.apache.bookkeeper-bookkeeper-server-4.14.3.jar:4.14.3]
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] 	at org.apache.bookkeeper.bookie.BookieShell.run(BookieShell.java:2275) [org.apache.bookkeeper-bookkeeper-server-4.14.3.jar:4.14.3]
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] 	at org.apache.bookkeeper.bookie.BookieShell.main(BookieShell.java:2366) [org.apache.bookkeeper-bookkeeper-server-4.14.3.jar:4.14.3]
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] Exception in thread "main" com.google.common.util.concurrent.UncheckedExecutionException: Failed to create zookeeper client to pulsar-ci-zookeeper:2281
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] 	at org.apache.bookkeeper.tools.cli.commands.bookies.InstanceIdCommand.apply(InstanceIdCommand.java:61)
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] 	at org.apache.bookkeeper.bookie.BookieShell$WhatIsInstanceId.runCmd(BookieShell.java:1492)
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] 	at org.apache.bookkeeper.bookie.BookieShell$MyCommand.runCmd(BookieShell.java:238)
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] 	at org.apache.bookkeeper.bookie.BookieShell.run(BookieShell.java:2275)
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] 	at org.apache.bookkeeper.bookie.BookieShell.main(BookieShell.java:2366)
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] Caused by: org.apache.bookkeeper.meta.exceptions.MetadataException: Failed to create zookeeper client to pulsar-ci-zookeeper:2281
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] 	at org.apache.bookkeeper.meta.zk.ZKMetadataDriverBase.initialize(ZKMetadataDriverBase.java:227)
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] 	at org.apache.bookkeeper.meta.zk.ZKMetadataBookieDriver.initialize(ZKMetadataBookieDriver.java:60)
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] 	at org.apache.bookkeeper.meta.MetadataDrivers.runFunctionWithMetadataBookieDriver(MetadataDrivers.java:345)
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] 	at org.apache.bookkeeper.meta.MetadataDrivers.runFunctionWithRegistrationManager(MetadataDrivers.java:372)
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] 	at org.apache.bookkeeper.tools.cli.commands.bookies.InstanceIdCommand.apply(InstanceIdCommand.java:49)
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] 	... 4 more
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] Caused by: org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] 	at org.apache.zookeeper.KeeperException.create(KeeperException.java:102)
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] 	at org.apache.bookkeeper.zookeeper.ZooKeeperWatcherBase.waitForConnection(ZooKeeperWatcherBase.java:159)
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] 	at org.apache.bookkeeper.zookeeper.ZooKeeperClient$Builder.build(ZooKeeperClient.java:260)
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] 	at org.apache.bookkeeper.meta.zk.ZKMetadataDriverBase.initialize(ZKMetadataDriverBase.java:207)
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] 	... 8 more
[pod/pulsar-ci-bookie-init-pcxzk/pulsar-ci-bookie-init] 14:46:37.603 [epollEventLoopGroup-2-1] INFO  org.apache.zookeeper.ClientCnxnSocketNetty - channel is told closing
```

**Comment by lhotari** [comment]
It's possible that the Zookeeper issue is simply caused by the probe getting stuck.
The changes in #179 fix the issue for 1.20+ . I'll send a separate PR to address the issue for Kubernetes <1.20.

**Comment by lhotari** [comment]
Rebased after #214 changes. Let's see if the Zookeeper TLS tests pass now.

**Comment by lhotari** [comment]
All tests pass now. I'll inform about this [on the dev mailing list thread](https://lists.apache.org/thread/619tpn6q5xbbhngwsmhtq3121vhjxpt4).

**Review by lhotari — APPROVED** [review]

**Comment by lhotari** [comment]
Closing and re-opening to run the tests one more time to see that the problem is fixed.

**Review by lhotari — CHANGES_REQUESTED** [review]
Problems with ZK & TLS aren't resolved yet.

**Comment by lhotari** [comment]
I'm hoping to get more logs from the failure after #215 changes are in place in CI.

**Comment by lhotari** [comment]
I finally got some logs from CI. It looks like the metadata initialization job is stuck. I'm adding timeouts in #218 to see if that could help mitigate the issue. 

I'm aware of a Zookeeper fix in the works for https://issues.apache.org/jira/browse/ZOOKEEPER-3988 . However, I haven't been able to find signs of ZOOKEEPER-3988 issue in the logs.

**Comment by lhotari** [comment]
Promising changes from @frederic-kneier in https://github.com/apache/pulsar/pull/14088 . It might resolve the issue that has been blocking us from upgrading to Pulsar 2.8.x in the Helm chart.

**Comment by lhotari** [comment]
Rebased on latest master branch changes.

**Comment by frankjkelly** [comment]
@lhotari are any of these changes (esp. the JVM setting changes) backwards incompatible with `2.7.x` Pulsar? Just wondering if I can mix-and-match this `2.8.x` helm chart and override the image tags with a `2.7.x` pulsar image? Thanks!

**Comment by michaeljmarshall** [comment]
We've moved passed 2.8, so I am going to close this PR.

**Pull request closed without merging**
