### PR TITLE
Remove breaking labelmap actions, #226, #100

### LINKED ISSUE #226: PodMonitor: dynamic labelMap-action breaking since prom-operator 0.54
**Describe the bug**
Dynamic labelmap-action in the current podMonitor-templates causes prom-operator skipping the PodMonitor altogether.

**To Reproduce**
1. Install [kube-prometheus-stack>=32.2.0](https://github.com/prometheus-community/helm-charts/releases/tag/kube-prometheus-stack-32.2.0 or [prometheus-operator>=0.54](https://github.com/prometheus-operator/prometheus-operator/tree/v0.54.0)
2. Install pulsar-helm-chart with `podMonitors` enabled, e.g. [zookeeper](https://github.com/apache/pulsar-helm-chart/blob/master/charts/pulsar/values.yaml#L304)
3. See your metrics disappear
4. See error in prometheus-operator-logs

```
level=warn ts=2022-02-10T21:35:52.803132682Z caller=operator.go:1957 component=prometheusoperator msg="skipping podmonitor" error="\"\" is invalid 'replacement' for labelmap action" podmonitor=pulsar/pulsar-recovery namespace=observability prometheus=prometheus-community-kube-prometheus
level=warn ts=2022-02-10T21:35:52.803317285Z caller=operator.go:1957 component=prometheusoperator msg="skipping podmonitor" error="\"\" is invalid 'replacement' for labelmap action" podmonitor=pulsar/pulsar-zookeeper namespace=observability prometheus=prometheus-community-kube-prometheus
level=warn ts=2022-02-10T21:35:52.803459387Z caller=operator.go:1957 component=prometheusoperator msg="skipping podmonitor" error="\"\" is invalid 'replacement' for labelmap action" podmonitor=pulsar/pulsar-broker namespace=observability prometheus=prometheus-community-kube-prometheus
level=warn ts=2022-02-10T21:35:52.803597189Z caller=operator.go:1957 component=prometheusoperator msg="skipping podmonitor" error="\"\" is invalid 'replacement' for labelmap action" podmonitor=pulsar/pulsar-proxy namespace=observability prometheus=prometheus-community-kube-prometheus
```

**Expected behavior**

**Screenshots**
image

**Additional context**
See related issue / change
- https://github.com/prometheus-operator/prometheus-operator/issues/3942#issuecomment-1035552992

### PR DESCRIPTION
**Pull request by mkoertgen**
Fixes #226

### Motivation

*Explain here the context, and why you're making that change. What is the problem you're trying to solve.*

### Modifications

*Describe the modifications you've done.*

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

### CODE REVIEW

**Review by lhotari — APPROVED** [review]
LGTM. Thanks for the contribution @mkoertgen . 

@addisonj @tuteng @sijie @michaeljmarshall Please review this PR.

**Comment by Rohlik** [comment]
I just hit on this problem too. Looking forward to see this PR merged 🙏🏽 .

**Comment by michaeljmarshall** [comment]
@mkoertgen - thanks for your contribution. Do we still need this PR? Based on the discussion in https://github.com/prometheus-operator/prometheus-operator/issues/3942, it seems like a prometheus operator bug that is already fixed in `0.54.1`. I only skimmed that issue, so please correct me if I am mistaken. Thanks.

**Comment by Rohlik** [comment]
@michaeljmarshall 
Verified with Prometheus Operator `0.54.1` and it works even without this PR.

**Comment by mkoertgen** [comment]
Hi @michaeljmarshall ,

Yes, meanwhile the prom-operator-team fixed labelmap validation, so this PR can probably be skipped & closed without merging. 
Users should be referred to upgrading prom-operator.

We could still ask ourselves why mapping all labels from the pod is a good idea, though. 
In my humble opiniont, users should be advised to add labels directly to the servicemonitor.

**Pull request closed without merging**
