### PR TITLE
anti-affinity rules refactor and default image tags

### PR DESCRIPTION
**Pull request by EladDolev**
Fixes default anit-affinity type not being used

### Motivation

make life easier, fix broken stuff and add the ability to set `topologyKey`

### Modifications

- add a default image specifications for pulsar components
- a small refactor to anti-affinity rules, add `topologyKey`, and have defaults work
- use `publishNotReadyAddresses` correctly, expose it as a parameter, and remove deprecated alpha annotation

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### CODE REVIEW

**Comment by EladDolev** [comment]
Hey friends

Thinking of adding the ability to set Pod Topology Spread Constraints and enable them by default
https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/

Also thinking of updating labels according to best practices
https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/
https://helm.sh/docs/chart_best_practices/labels/

I can do it on this PR, or create another one
These are breaking changes BTW

**Comment by sijie** [comment]
@EladDolev Regarding the breaking changes, it would be good to do it in a separate PR

**Comment by lhotari** [comment]
@EladDolev good work!

> use publishNotReadyAddresses correctly, expose it as a parameter, and remove deprecated alpha annotation

this change would be valuable. Please send it as a separate PR.

**Comment by lhotari** [comment]
Closing this PR as outdated.

**Pull request closed without merging**
