### PR TITLE
Fix cluster initialize blocked when fail: #175

### LINKED ISSUE #175: Create may block if the initialize cluster job fails
**Describe the bug**
In the pulsar-init Job, the init script is:

``` shell
bin/pulsar initialize-cluster-metadata \
                --cluster pulsar \
                --zookeeper pulsar-zookeeper:2181 \
                --configuration-store pulsar-zookeeper:2181 \
                --web-service-url http://pulsar-broker.test.svc.cluster.local:8080/ \
                --web-service-url-tls https://pulsar-broker.test.svc.cluster.local:8443/ \
                --broker-service-url pulsar://pulsar-broker.test.svc.cluster.local:6650/ \
                --broker-service-url-tls pulsar+ssl://pulsar-broker.test.svc.cluster.local:6651/ || true;
```

The `|| true` at the end makes the Job not fail even when error occurs in initializing metadata.

Usually it's ok, for there's a init container checking zookeeper status, but if we have a bad day when zookeeper goes down just after init container succeeded, and before main container start, the cluster metadata will never be initialized. Which will result in pulsar components blocked forever. like in issue: #124 

We should remove the tail || true, let the job restart if failed.

**To Reproduce**
`TBD`

**Expected behavior**
init Job will keep retrying when initializing metadata failed, until success.

**Screenshots**
`TBD`

**Desktop (please complete the following information):**
 - OS: KinD on OS.X

**Additional context**
ref: milvus-io/milvus-operator#40

### PR DESCRIPTION
**Pull request by haorenfsa**
### Motivation

Fixes #175 

### Modifications

Cluster init job retries every 3 sec before success

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

### CODE REVIEW

**Review by MarvinCai — APPROVED** [review]
lgtm

**Comment by haorenfsa** [comment]
@eolivelli  have a look?

**Review by lhotari — CHANGES_REQUESTED** [review]
Instead of adding the loop to retry forever, I'd suggest to remove the `|| true` and change `restartPolicy: Never` to `restartPolicy: OnFailure`.

**Review by michaeljmarshall — DISMISSED** [review]
I agree with @lhotari. Let's rely on Kubernetes to restart the pod. That'll also give us an increasing back off for free.

**Comment by haorenfsa** [comment]
updated

**Review by lhotari — APPROVED** [review]
LGTM

**Comment by frankjkelly** [comment]
@lhotari  without a change in Chart version will a new release be created? CC: @sijie

**Comment by lhotari** [comment]
> @lhotari without a change in Chart version will a new release be created? CC: @sijie

correct. Here's the logs: https://github.com/apache/pulsar-helm-chart/runs/4715446366?check_suite_focus=true .
I think it's useful to have multiple PRs batched into a release.

**Comment by frankjkelly** [comment]
@lhotari Sounds good, thanks for the clarification.

**Comment by michaeljmarshall** [comment]
>  I think it's useful to have multiple PRs batched into a release.

+1

**Pull request merged**
