### PR TITLE
Updating pods on configmap change

### LINKED ISSUE #71: Restarting pods after config map change
**Is your feature request related to a problem? Please describe.**
Pods are not restarting when config maps are changed after changing values.yaml file, so they need to be restarted manually in order to pick up new values from config map.

**Describe the solution you'd like**
In my case pods need to restart after corresponding config map change, so one of solutions that developer from pulsar suggested me is adding this https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments, so it has to be added in every statefulset in templates.

**Describe alternatives you've considered**
As I mentioned alternative is to delete pods manually, or some other solution that I am not aware now.

**Additional context**
So is this conclusion correct, do pods need to be restarted after config maps change?

### PR DESCRIPTION
**Pull request by milos-matijasevic**
Fixes #71 

### Motivation

Pods are not restarting when config maps are changed after changing values.yaml file, so they need to be restarted manually in order to pick up new values from config map. 

### Modifications

As I mentioned `restartPodsOnConfigMapChange` flag for each component is added in values.yaml file whether to restart pods on configmap change or not, default is `false`.
In statefulset templates for each component is added part which is adding annotation that contains hash of corresponding configmap if `restartPodsOnConfigMapChange` is `true`, which will cause pods to restart if corresponding configmap has been changed (https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments).

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

### CODE REVIEW

**Comment by milos-matijasevic** [comment]
This already exists in kafkaesque-io pulsar chart, https://github.com/kafkaesque-io/pulsar-helm-chart/blob/master/helm-chart-sources/pulsar/templates/bookkeeper-statefulset.yaml#L53 in pretty much same form, i just added config flag for every deployment/statefulset separately

**Comment by jeantil** [comment]
The CI error suggests that there was an issue with the ci platform when your PR was submitted, ulterior PRs seem to have passed the tests. Can you try to rebase on the latest master to trigger a new CI build ? (I'm quite interested in this too :D )

**Comment by milos-matijasevic** [comment]
hello, @sijie  after #76 is merged i want to rerun CI tests, is there way to do it ?

**Comment by sijie** [comment]
@milos-matijasevic You can rebase your pull request to the latest master and push to your branch. It then will trigger the CI to run again.

**Review by sijie — APPROVED** [review]

**Review by wolfstudy — APPROVED** [review]

**Review by sijie — APPROVED** [review]

**Comment by MMeent** [comment]
I've noticed that there are indentation issues for several of the templates, so I've filed #116, and created a PR at #117 to fix those specific issues.

**Pull request merged**
