### PR TITLE
Feature/pulsar manager v0.2.0 with jwt setup admin account creation

### LINKED ISSUE #31: Param pulsar_manager.admin.user/pulsar_manager.admin.password used in the wrong place
**Describe the bug**
I am try to set pulsar_manager.admin.user/pulsar_manager.admin.password for login pulsar-manager ui, But it's actually used as the account/password for outside PostgreSQL instance.

**To Reproduce**
helm upgrade --install pulsar charts/pulsar --set pulsar_manager.admin.user=pulsarpulsar --set pulsar_manager.admin.password=pulsarpulsar  -n pulsar

```
org.postgresql.util.PSQLException: FATAL: role "pulsarpulsar" does not exist
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440) ~[postgresql-42.2.5.jar:42.2.5]
	at org.postgresql.core.v3.QueryExecutorImpl.readStartupMessages(QueryExecutorImpl.java:2559) ~[postgresql-42.2.5.jar:42.2.5]
	at org.postgresql.core.v3.QueryExecutorImpl.<init>(QueryExecutorImpl.java:133) ~[postgresql-42.2.5.jar:42.2.5]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:250) ~[postgresql-42.2.5.jar:42.2.5]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49) ~[postgresql-42.2.5.jar:42.2.5]
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195) ~[postgresql-42.2.5.jar:42.2.5]
	at org.postgresql.Driver.makeConnection(Driver.java:454) ~[postgresql-42.2.5.jar:42.2.5]
```

### LINKED ISSUE #86: Pulsar manager mount private/public key for token generation
When activate JWT token authentication it will be nice to be able to mount the 

- {{ .Release.Name }}-token-asymmetric-key
or 
- {{ .Release.Name }}-token-symmetric-key

### Evolution
It will be nice to have this feature in the pulsr-manager-deployment.yaml
image

### LINKED ISSUE #108: Pulsar manager always uses default user/password
#### Expected behavior
Providing non default username and password for Pulsar Admin Manager component should actually change the username and password

#### Actual behavior
Pulsar admin manager always uses the default username and password (not secure)

#### Steps to reproduce
`helm upgrade --install --set pulsar_manager.admin.password=myspecialpassword --set pulsar_manager.admin.user=myspecialuser --set initialize=true --values examples/values-minikube.yaml --namespace pulsar pulsar-mini apache/pulsar`

*I am aware that default chart does not restart pods if the secret changes, but lets say this is fresh install (also the case). 

#### System configuration
**Helm chart commit**: c059ea25d80d6165b67ee163252a682198d8933f

Using all default values for minkube

### LINKED ISSUE #133: When JWT configuration is enabled, where pulsar manager New Environment will report "This environment is error. Please check it"
**Describe the bug**

**To Reproduce**
1. Go to 'K8S+helm + pulsar 2.7.2'  prepare
./scripts/pulsar/prepare_helm_release.sh -n pulsar-dev -k pulsar-dev --symmetric
2. install  pulsar
helm upgrade --install  pulsar-dev $NAMESPACE/pulsar \
 --timeout 10m \
 --set namespace=pulsar-dev \
 --set namespaceCreate=false \
 --set initialize=true \
 --set affinity.anti_affinity=true \
 --set auth.authentication.enabled=true \
 --set auth.authentication.jwt.usingSecretKey=true \
 --set auth.authorization.enabled=true \
 --set bookkeeper.volumes.journal.storageClassName=managed-nfs-storage2 \
 --set bookkeeper.volumes.ledgers.storageClassName=managed-nfs-storage

all pods are running :
[Martin@iZwz9cs3943soptmvn8mbrZ ~]$ kubectl get pod  -n pulsar-dev                      
NAME                                         READY   STATUS      RESTARTS   AGE
nfs-client-provisioner-5c997cc6c8-kpv99      1/1     Running     0          6d11h
nfs-client-provisioner2-8675974896-rmzpv     1/1     Running     0          6d8h
pulsar-dev-bookie-0                          1/1     Running     0          26m
pulsar-dev-bookie-1                          1/1     Running     0          26m
pulsar-dev-bookie-2                          1/1     Running     0          26m
pulsar-dev-bookie-init-42p64                 0/1     Completed   0          26m
pulsar-dev-broker-0                          1/1     Running     1          26m
pulsar-dev-broker-1                          1/1     Running     1          26m
pulsar-dev-broker-2                          1/1     Running     0          26m
pulsar-dev-grafana-9468669c6-sgbh7           1/1     Running     0          26m
pulsar-dev-prometheus-59bddccd9c-mq56b       1/1     Running     0          26m
pulsar-dev-proxy-0                           1/1     Running     0          26m
pulsar-dev-proxy-1                           1/1     Running     0          26m
pulsar-dev-proxy-2                           1/1     Running     0          26m
pulsar-dev-pulsar-init-gwpzm                 0/1     Completed   0          26m
pulsar-dev-pulsar-manager-67b964b786-fr87l   1/1     Running     0          26m
pulsar-dev-recovery-0                        1/1     Running     0          26m
pulsar-dev-toolset-0                         1/1     Running     0          26m
pulsar-dev-zookeeper-0                       1/1     Running     0          26m
pulsar-dev-zookeeper-1                       1/1     Running     0          25m
pulsar-dev-zookeeper-2                       1/1     Running     0          25m

3. go to  pulsar manager and  New Environment
report  "This environment is error. Please check it"

3. check the logs :    kubectl logs  pulsar-dev-proxy-1 -n pulsar-dev 

"11:57:21.249 [pulsar-proxy-io-2-1] INFO  org.apache.pulsar.proxy.server.ProxyConnection - [/10.92.251.122:38809] New connection opened
11:57:21.249 [pulsar-proxy-io-2-1] WARN  io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
11:57:21.249 [pulsar-proxy-io-2-1] WARN  org.apache.pulsar.proxy.server.ProxyConnection - [/10.92.251.122:38809] Got exception NativeIoException : readAddress(..) failed: Connection reset by peer null
11:57:21.249 [pulsar-proxy-io-2-1] INFO  org.apache.pulsar.proxy.server.ProxyConnection - [/10.92.251.122:38809] Connection closed
11:57:21.852 [pulsar-proxy-io-2-2] INFO  org.apache.pulsar.proxy.server.ProxyConnection - [/10.92.251.124:65366] New connection opened
11:57:21.852 [pulsar-proxy-io-2-2] WARN  io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
11:57:21.852 [pulsar-proxy-io-2-2] WARN  org.apache.pulsar.proxy.server.ProxyConnection - [/10.92.251.124:65366] Got exception NativeIoException : readAddress(..) failed: Connection reset by peer null"

If I do not  used this  two parameters  install， there is no problem:
 --set auth.authentication.enabled=true 
 --set auth.authentication.jwt.usingSecretKey=true 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by csthomas1**
Fixes #133
Fixes #108 
Fixes #86 
Fixes #31 

### Motivation

The docker image for Pulsar Manager v0.2.0 includes support for JWT-based configurations, so long as the appropriate environment variables are specified:
- JWT_TOKEN
- PRIVATE_KEY/PUBLIC_KEY -or- SECRET_KEY

The k8s secrets that can populate each of the above environment variables are created by the 'prepare_helm_release.sh' script when it is run prior to installation of the helm chart. Unfortunately, the helm chart doesn't current provide a way to directly expose these secrets to the Pulsar Manager deployment. Instead, it requires that these values be separately set in the "configData" map of the "pulsar_manager" section, which creates the opportunity for them to go out of sync. Further, it exposes in clear text potentially sensitive values (the superuser token and the key material) in the ConfigMap alongside other environment settings.

Pulsar Manager v0.2.0 has also introduced a user management capability that is enabled by default, and requires that the initial admin/superuser account be created via web service call (see https://github.com/apache/pulsar-manager/blob/master/README.md).

Finally, the current helm chart mistakenly conflates the Pulsar Manager admin user's credentials with those of the Postgres user account used to establish a connection to the Pulsar Manager's internal database -- it mounts the admin user's credentials secret to the "USERNAME" and "PASSWORD" environment variables, despite the fact that these control only the datasource connection parameters as described above. Further, with the current secret mounting approach, changing the admin credentials actually breaks the Pulsar Manager deployment because the pulsar database credentials are hardcoded in the postgres db initialization script.

The changes included in this PR do the following:
1. Enable mounting of the appropriate JWT and key secrets to the appropriate environment variables when JWT authentication is enabled;
2. Automatically (when requested) creates the initial admin account via web service call on container startup. This initial account will be configured with the credentials contained in the manager's admin secret.
3. The manager's admin secret will no longer be used to set the USERNAME and PASSWORD environment variables for reasons described above; hence, changing the admin secret will now correctly only affect the credentials recognized as the default login to the Pulsar Manager and will no longer break the connection to Pulsar Manager's internal database.

### Modifications

1. In charts/pulsar/values.yaml:
- Added auth.superUsers type "manager," which defaults to blank. Setting a value here determines the JWT secret (generated by the prepare_helm_release.sh script) that will be used by the Pulsar Manager to communicate with the Pulsar brokers when JWT authentication is enabled.
- Added pulsar_manager.autoCreateAdminAccount, which defaults to true. When this value is set to true, a sidecar will be added to the Pulsar Manager pod that will create the admin's account from the configured credentials when the container launches.
- Added 'USERNAME' and 'PASSWORD' with values of pulsar/pulsar to pulsar_manager.configData, since these values currently must agree with the hardcoded values in the database initialization script
2. In charts/pulsar/templates/pulsar-manager-deployment.yaml:
- REMOVED the mounts of the pulsar admin secret to the USERNAME and PASSWORD environment variables.
- ADDED env secretKeyRefs for JWT_TOKEN to the "manager" superUser token when jwt authentication is enabled
- ADDED env file path value for SECRET_KEY when jwt authentication is enabled and jwt.usingSecretKey is true
- ADDED env file path value for PRIVATE_KEY and PUBLIC_KEY when jwt authentication is enabled and jwt.usingSecretKey is false
- ADDED volume mount for pulsar-manager-keys when jwt authentication is enabled
- ADDED volume for the symmetric token signing key when jwt authentication is enabled and jwt.usingSecretKey is true
- ADDED volume for the asymmetric token signing key when jwt authentication is enabled and jwt.usingSecretKey is false
- ADDED sidecar container to initialize admin user account when pulsar_manager.autoCreateAdminAccount is true.
  Upon launch, the sidecar will attempt to curl the pulsar-manager's main page every 3 seconds until it receives a successful status. At that point, it will perform the procedure described in the pulsar manager README.md (get a CSRF token, then
make another service call to create the admin account).  It will then sleep forever.
### Verifying this change

- [x] Make sure that the change passes the CI checks.

### CODE REVIEW

**Comment by csthomas1** [comment]
Note -- I'm working on expanding the jwt-symmetric and jwt-asymmetric test cases to also test that the pulsar manager is correctly configured when jwt authentication is enabled.

**Review by tuteng — APPROVED** [review]

**Comment by mzwennes** [comment]
@tuteng Could these changes be merged? I would love to be able to set the JWT via a Secret.

**Comment by lhotari** [comment]
@csthomas1 would you like to rebase the changes?

@Mortom123 Please review this. Would something like this be useful?

**Comment by lhotari** [comment]
> Yes, I'll try to take a look at this later this week.

@csthomas1 Awesome! Please ensure compatibility with changes that @Mortom123 made in #457. Looking forward to your contribution!

**Comment by lhotari** [comment]
@csthomas1 It's possible to get a ssh shell into the build VM if you open a PR to your own fork. This comment and screenshot might help with that: https://github.com/apache/pulsar-helm-chart/pull/448#issuecomment-1919052024

**Review by lhotari — APPROVED** [review]
Great job! Thanks for the contribution @csthomas1 !

**Pull request merged**
