### PR TITLE
fix: proxy should not use priviledged port numbers

### PR DESCRIPTION
**Pull request by chrisjohnson00**
This fixes issue #335

### Motivation

Fixing the port 80 binding issue in issue #335 

### Modifications

Changed from port 80 -> 8080 for HTTP and 443 -> 8443 for HTTPS

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

### CODE REVIEW

**Review by michaeljmarshall — APPROVED** [review]
LGTM. Thanks for your contribution @chrisjohnson00!

The change to run the container as a non-root user broke this part of the helm chart. Another option would be to let the proxy service continue using ports 80 and 443 while mapping those to 8080 and 8443 on the proxy container. I don't think that is necessary though if we correctly document this change in the release notes.

**Comment by chrisjohnson00** [comment]
> LGTM. Thanks for your contribution @chrisjohnson00!
> 
> The change to run the container as a non-root user broke this part of the helm chart. Another option would be to let the proxy service continue using ports 80 and 443 while mapping those to 8080 and 8443 on the proxy container. I don't think that is necessary though if we correctly document this change in the release notes.

Oh, I hadn't noticed that both the service and the deployment shared these values.  Wouldn't this make it a breaking change since the service ports would change?  I'd be happy to update it so it is not a BC!

**Comment by michaeljmarshall** [comment]
> Oh, I hadn't noticed that both the service and the deployment shared these values. Wouldn't this make it a breaking change since the service ports would change? I'd be happy to update it so it is not a BC!

Sorry for my delayed response. Yes, it would make it a breaking change. It'd be great if we can avoid the breaking change, thanks!

**Comment by chrisjohnson00** [comment]
> > Oh, I hadn't noticed that both the service and the deployment shared these values. Wouldn't this make it a breaking change since the service ports would change? I'd be happy to update it so it is not a BC!
> 
> Sorry for my delayed response. Yes, it would make it a breaking change. It'd be great if we can avoid the breaking change, thanks!

I've pushed up a change that makes this backward compatible.  Let me know what you think.
I've introduced using named ports for the `targetPort` in the service, which helps to further protect future change from being breaking.  Since the port names in the service and stateful set were the same, I prefixed the ports in the sts with `sts-` to distinguish them.

**Comment by lhotari** [comment]
closing and re-opening to trigger new CI run

**Pull request merged**
