### PR TITLE
Add kubeVersion to Chart.yaml to enforce minimum Kubernetes version

### PR DESCRIPTION
**Pull request by lhotari**
k8s 1.21 is the minimum required version

### CODE REVIEW

**Review by frankjkelly — APPROVED** [review]
Nice LGTM!

**Comment by frankjkelly** [comment]
FYI @lhotari I noticed that the CI test `Upgrade latest released version - k8s 1.27.3 - upgrade` failed - is that expected?

**Comment by lhotari** [comment]
> FYI @lhotari I noticed that the CI test `Upgrade latest released version - k8s 1.27.3 - upgrade` failed - is that expected?

I'm re-running the failed jobs to see if it was a flakiness issue.

**Comment by frankjkelly** [comment]
> > FYI @lhotari I noticed that the CI test `Upgrade latest released version - k8s 1.27.3 - upgrade` failed - is that expected?
> 
> I'm re-running the failed jobs to see if it was a flakiness issue.

Sounds good - should the repo have branch protection settings to prevent a merge?

**Pull request merged**
