### PR TITLE
Bump Pulsar version to 2.8.1

### PR DESCRIPTION
**Pull request by hangc0276**
### Motivation
Currently, Pulsar 2.8.1 has been released, we can update the pulsar version in helm chart.

### Modifications
1. Bump Pulsar version to 2.8.1

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

### CODE REVIEW

**Comment by danielorf** [comment]
v2.8.0 is currently blocked ([related PR](https://github.com/apache/pulsar-helm-chart/pull/130)), is v2.8.1 reliant on v2.8.0 being released first?

**Comment by thomasechen** [comment]
Pulasr 2.9.1 was released, could we have the helm that support these two releases?

**Comment by eolivelli** [comment]
@thomasechen you can override the docker image in your values.yaml file

**Comment by lhotari** [comment]
superseded by #190

**Pull request closed without merging**
