### PR TITLE
Test with Kubeadm 1.24.12

### PR DESCRIPTION
**Pull request by michaeljmarshall**
### Motivation

kubeadm failed to start in several recent tests. I noticed we're running with an old version of kubeadm. This PR upgrades to a more recent version. Specifically, the oldest one still getting patch support from the upstream Kubernetes project.

### Modifications

Update the test script.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

### CODE REVIEW

**Comment by michaeljmarshall** [comment]
@lhotari - these tests are failing because kubadm isn't starting. I did some quick searching and couldn't find an explanation. Do you have any suggestions?

**Comment by lhotari** [comment]
> @lhotari - these tests are failing because kubadm isn't starting. I did some quick searching and couldn't find an explanation. Do you have any suggestions?

There's #369 where things seem to mostly succeed.

**Comment by lhotari** [comment]
A specific kind version supports only specific kindest/node docker image tags. These are listed in the release notes: https://github.com/kubernetes-sigs/kind/releases

**Comment by lhotari** [comment]
closing since CI is fixed with #370

**Pull request closed without merging**
